server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/skillmatrix}
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:1234}
  liquibase:
    enabled: true
    change-log: classpath:root-changelog.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: alpha

security:
  jwt:
    secret: ${JWT_SECRET_KEY:secret}
    hours: ${JWT_HOURS:24}

