spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillmatrix
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
